### ISSUE TITLE
package bash overwrites default /opt/etc/profile

### ISSUE THREAD

**Issue by Napkin** [boretom/optware#3]
Package bash contains /opt/etc/profile, overwriting the version already installed by the ipkg package.

This effectively disables parsing of /opt/etc/profile.d/, which is required to have /opt/bin & /opt/sbin in PATH.

Also, uninstalling bash deletes /opt/etc/profile.

How about giving bash the same config as in ipkg or using /opt/etc/profile.d/bash?

**Comment by boretom** [comment]
Please use [Entware](https://github.com/Entware/Entware.git)
